In [97]:
import torch
from torch.nn import RNN

### part one

In [209]:
# input size == number of input features
# hidden size == number of output features
# num_layers == number of RNN block that sequence.
model = RNN(1, 1, nonlinearity='relu', bias=False)

In [211]:
# we have two weights (Wih & Whh)
for i in model.parameters():
    print(i)

Parameter containing:
tensor([[0.4775]], requires_grad=True)
Parameter containing:
tensor([[-0.4359]], requires_grad=True)


In [212]:
# re-initialize
def init(submodule):
    for para in submodule.parameters():
        # torch.nn.init.normal_(para,1, 1)
        torch.nn.init.constant_(para, 1)
model.apply(init)

RNN(1, 1, bias=False)

In [213]:
for i in model.parameters():
    print(i)

Parameter containing:
tensor([[1.]], requires_grad=True)
Parameter containing:
tensor([[1.]], requires_grad=True)


In [214]:
# data =(N= Everything , L=Everything , H_in= F_in (number of input features))
data = torch.tensor([1,2,3], dtype=torch.float).view(1,3,1)
print(data.shape)
# N=1, L=3, F_in =1

torch.Size([1, 3, 1])


In [216]:
out, h_n = model(data)

In [220]:
print(out)
print(out.shape)
print(h_n)
print(h_n.shape)

tensor([[[1.],
         [2.],
         [3.]]], grad_fn=<StackBackward0>)
torch.Size([1, 3, 1])
tensor([[[1.],
         [2.],
         [3.]]], grad_fn=<StackBackward0>)
torch.Size([1, 3, 1])


### part two

In [230]:
model = RNN(4, 2, nonlinearity='relu', bias=False)
model.apply(init)

RNN(4, 2, bias=False)

In [231]:
for i in model.parameters():
    print(i.shape)

torch.Size([2, 4])
torch.Size([2, 2])


In [232]:
# L = 100 samples
# N = 5 subject
# F_in 4 Channels
data = torch.empty((100, 5, 4)).normal_(0,1)
data.shape

torch.Size([100, 5, 4])

In [233]:
out, h_n = model(data)
print(out.shape)
print(h_n.shape)

torch.Size([100, 5, 2])
torch.Size([1, 5, 2])


### part three

In [234]:
# EEG Real
model = RNN(16, 10, nonlinearity='relu', bias=True)
model.apply(init)

RNN(16, 10)

In [253]:
param_names = iter(model.named_parameters())
for param in model.parameters():
    print(next(param_names)[0])
    print(param.shape)

weight_ih_l0
torch.Size([10, 16])
weight_hh_l0
torch.Size([10, 10])
bias_ih_l0
torch.Size([10])
bias_hh_l0
torch.Size([10])


In [254]:
data = torch.empty((7000, 200, 16)).normal_(0,1)
data.shape

torch.Size([7000, 200, 16])

In [255]:
out, h_n = model(data)
print(out.shape)
print(h_n.shape)

torch.Size([7000, 200, 10])
torch.Size([1, 200, 10])
