In [6]:
import torch
from torch import nn
from torch.nn.parameter import Parameter

# Module (Parents class)

In [337]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()

        self.dense1 = self.dense(784, 256)

    def dense(self, node_i, node_o):
        return nn.Sequential(
            nn.Linear(node_i, node_o),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return nn.Sequential(
            self._modules
        )(x)

In [344]:
# get instance from my class
model = Net()
# data
data=torch.normal(mean=torch.zeros(1000,784), std = torch.ones(1000,784))

# Properties

### training

In [345]:
# by default this property for your module always TRUE
model.training

True

In [346]:
# but, if I use this method (one of methods of nn.Module), this property will change.
model.eval()
model.training

False


### _modules

In [347]:
# model have just two submodule
print(len(model._modules))

1


In [348]:
model._modules

OrderedDict([('dense1',
              Sequential(
                (0): Linear(in_features=784, out_features=256, bias=True)
                (1): ReLU(inplace=True)
              ))])

### _parameters

In [349]:
# my model have NOT parameter.
model._parameters

OrderedDict()

In [350]:
# also for "dense1" submodule, have NOT parameters
model.get_submodule('dense1')._parameters

OrderedDict()

In [351]:
# but, here we have two Parameter.
model.get_submodule('dense1').get_submodule('0')._parameters

OrderedDict([('weight',
              Parameter containing:
              tensor([[-0.0164, -0.0070, -0.0192,  ..., -0.0062,  0.0157,  0.0218],
                      [-0.0002, -0.0090, -0.0345,  ..., -0.0232, -0.0289, -0.0096],
                      [ 0.0284, -0.0061,  0.0154,  ...,  0.0067,  0.0284, -0.0330],
                      ...,
                      [ 0.0323, -0.0185, -0.0141,  ..., -0.0013, -0.0272, -0.0304],
                      [ 0.0042,  0.0242,  0.0149,  ...,  0.0307,  0.0130, -0.0241],
                      [-0.0147, -0.0175,  0.0271,  ...,  0.0081, -0.0058,  0.0226]],
                     requires_grad=True)),
             ('bias',
              Parameter containing:
              tensor([ 3.5076e-02, -8.2340e-03,  3.1857e-02,  2.5620e-02,  1.4391e-02,
                       2.1441e-02,  3.0662e-02, -1.4902e-02,  3.1847e-03, -1.6371e-02,
                       2.3757e-02, -3.5535e-02,  1.5013e-02, -2.0158e-02,  3.3936e-02,
                      -3.4409e-02,  9.9436e-03

In [352]:
# we add one additional property JUST to model (instance of class Net)
model.ali = nn.parameter.Parameter(torch.tensor([1,2,3], dtype = torch.float))
# NOW, our Module have Parameter.
print(model._parameters)

OrderedDict([('ali', Parameter containing:
tensor([1., 2., 3.], requires_grad=True))])


# Methods

### add_module

In [353]:
# data
data=torch.normal(mean=torch.zeros(1000,784), std = torch.ones(1000,784))

In [354]:
model = Net()
print(model)

Net(
  (dense1): Sequential(
    (0): Linear(in_features=784, out_features=256, bias=True)
    (1): ReLU(inplace=True)
  )
)


In [228]:
# add module
model.add_module('dense2', model.dense(256, 10))
print(model)

Net(
  (dense1): Sequential(
    (0): Linear(in_features=784, out_features=256, bias=True)
    (1): ReLU(inplace=True)
  )
  (dense2): Sequential(
    (0): Linear(in_features=256, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
)


In [229]:
# feed data
model(data).shape

torch.Size([1000, 10])

In [230]:
model(data).shape

torch.Size([1000, 10])

### get_submodule

In [355]:
# model : is sub-module of nn.Module (children of nn.Module)
# dense1 & dense2 : are sub-modules of model (children of model)
# 0 & 1 : are sub-modules of dense1&dense2 (children of dense1 and dense2)

model.get_submodule('dense1')

Sequential(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): ReLU(inplace=True)
)

In [356]:
model.get_submodule('dense1').get_submodule('0')

Linear(in_features=784, out_features=256, bias=True)

### get_parameter

In [183]:
model.get_submodule('dense1').get_submodule('0').get_parameter('weight')

Parameter containing:
tensor([[ 0.0138,  0.0048,  0.0201,  ..., -0.0185,  0.0333, -0.0121],
        [-0.0251,  0.0025, -0.0223,  ..., -0.0217, -0.0083,  0.0170],
        [ 0.0333, -0.0191, -0.0211,  ...,  0.0224,  0.0013,  0.0220],
        ...,
        [ 0.0179,  0.0356, -0.0293,  ...,  0.0242,  0.0310,  0.0072],
        [-0.0113, -0.0092,  0.0021,  ...,  0.0073, -0.0246, -0.0281],
        [ 0.0269,  0.0245,  0.0084,  ...,  0.0303,  0.0278, -0.0273]],
       requires_grad=True)

### children

In [186]:
ch = model.children() # remember : children method in nn.Module, is a iterator

for i in ch:
    print(i)

Sequential(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): ReLU(inplace=True)
)
Sequential(
  (0): Linear(in_features=256, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)


### apply

##### Mechanism

In [300]:
print(model)

Net(
  (dense1): Sequential(
    (0): Linear(in_features=784, out_features=256, bias=True)
    (1): ReLU(inplace=True)
  )
  (dense2): Sequential(
    (0): Linear(in_features=256, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
)


In [302]:
# sub-modules of my model
k=0
for i in model.children():
    print(i)
    k+=1
LU(inplace=Tprint("I have {} sub-module".format(k))

Sequential(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): ReLU(inplace=True)
)
Sequential(
  (0): Linear(in_features=256, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)
I have 2 sub-module


In [312]:
# "apply method" get a function on submodules.
def fn_1(submodule):
    print(" ")
    print(submodule)
    print(" ")

In [313]:
# How word apply
model.apply(fn_1)

 
Linear(in_features=784, out_features=256, bias=True)
 
 
ReLU(inplace=True)
 
 
Sequential(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): ReLU(inplace=True)
)
 
 
Linear(in_features=256, out_features=10, bias=True)
 
 
ReLU(inplace=True)
 
 
Sequential(
  (0): Linear(in_features=256, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)
 
 
Net(
  (dense1): Sequential(
    (0): Linear(in_features=784, out_features=256, bias=True)
    (1): ReLU(inplace=True)
  )
  (dense2): Sequential(
    (0): Linear(in_features=256, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
)
 


Net(
  (dense1): Sequential(
    (0): Linear(in_features=784, out_features=256, bias=True)
    (1): ReLU(inplace=True)
  )
  (dense2): Sequential(
    (0): Linear(in_features=256, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
)

In [310]:
# just find submodules in my model that is in nn.Linear class
def fn_2(submodule):
    if isinstance(submodule, nn.Linear):
        print(" ")
        print(submodule)
        print(" ")

In [311]:
model.apply(fn_2)

 
Linear(in_features=784, out_features=256, bias=True)
 
 
Linear(in_features=256, out_features=10, bias=True)
 


Net(
  (dense1): Sequential(
    (0): Linear(in_features=784, out_features=256, bias=True)
    (1): ReLU(inplace=True)
  )
  (dense2): Sequential(
    (0): Linear(in_features=256, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
)

In [314]:
# just find submodules in my model that is in nn.Linear class
def fn_3(submodule):
    if isinstance(submodule, nn.ReLU):
        print(" ")
        print(submodule)
        print(" ")

In [315]:
model.apply(fn_3)

 
ReLU(inplace=True)
 
 
ReLU(inplace=True)
 


Net(
  (dense1): Sequential(
    (0): Linear(in_features=784, out_features=256, bias=True)
    (1): ReLU(inplace=True)
  )
  (dense2): Sequential(
    (0): Linear(in_features=256, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
)

##### Application

In [317]:
print(model)

Net(
  (dense1): Sequential(
    (0): Linear(in_features=784, out_features=256, bias=True)
    (1): ReLU(inplace=True)
  )
  (dense2): Sequential(
    (0): Linear(in_features=256, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
)


In [330]:
def change_weight(submodule):
    if isinstance(submodule, nn.Linear):
        # we use this function because "torch.tensor.noraml_" isn't work on tensors that require_grad is true
        nn.init.normal_(submodule.weight, mean=0, std=0.01)
        print(f"{submodule.weight} has been changed")

In [331]:
model.get_submodule('dense1').get_submodule('0').weight

Parameter containing:
tensor([[-1.5091, -1.7819,  1.9765,  ...,  0.2571,  0.9224,  0.8038],
        [ 0.9659, -1.3345, -1.1959,  ..., -0.8096, -1.2213, -0.3076],
        [-0.5866,  0.8363, -1.8263,  ...,  0.1558,  0.7013, -2.5042],
        ...,
        [-0.5259,  0.6846, -0.1971,  ..., -0.7972,  0.3515,  1.3830],
        [ 0.5845, -0.8238,  1.5760,  ..., -0.4524, -1.0270, -1.5766],
        [ 0.0449, -0.0923, -1.2375,  ...,  0.2052,  0.7739, -1.6613]],
       requires_grad=True)

In [332]:
model.apply(change_weight)

Parameter containing:
tensor([[-0.0164,  0.0149,  0.0121,  ..., -0.0135, -0.0038,  0.0002],
        [ 0.0115,  0.0014,  0.0051,  ..., -0.0141, -0.0063, -0.0060],
        [-0.0099,  0.0091, -0.0016,  ...,  0.0149, -0.0142, -0.0043],
        ...,
        [ 0.0119, -0.0042,  0.0209,  ...,  0.0135,  0.0135,  0.0173],
        [-0.0136,  0.0200,  0.0035,  ..., -0.0014, -0.0106, -0.0118],
        [-0.0035,  0.0047,  0.0099,  ...,  0.0006, -0.0003, -0.0056]],
       requires_grad=True) has been changed
Parameter containing:
tensor([[-0.0004,  0.0041, -0.0039,  ..., -0.0046, -0.0099,  0.0157],
        [-0.0016,  0.0069, -0.0133,  ...,  0.0039, -0.0045,  0.0044],
        [-0.0075,  0.0056, -0.0033,  ...,  0.0047, -0.0174,  0.0044],
        ...,
        [-0.0157,  0.0063,  0.0094,  ...,  0.0008, -0.0067,  0.0038],
        [ 0.0001, -0.0131, -0.0051,  ..., -0.0123, -0.0041, -0.0007],
        [-0.0133,  0.0059, -0.0055,  ..., -0.0020, -0.0081,  0.0176]],
       requires_grad=True) has been changed


Net(
  (dense1): Sequential(
    (0): Linear(in_features=784, out_features=256, bias=True)
    (1): ReLU(inplace=True)
  )
  (dense2): Sequential(
    (0): Linear(in_features=256, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
)

In [333]:
model.get_submodule('dense1').get_submodule('0').weight

Parameter containing:
tensor([[-0.0164,  0.0149,  0.0121,  ..., -0.0135, -0.0038,  0.0002],
        [ 0.0115,  0.0014,  0.0051,  ..., -0.0141, -0.0063, -0.0060],
        [-0.0099,  0.0091, -0.0016,  ...,  0.0149, -0.0142, -0.0043],
        ...,
        [ 0.0119, -0.0042,  0.0209,  ...,  0.0135,  0.0135,  0.0173],
        [-0.0136,  0.0200,  0.0035,  ..., -0.0014, -0.0106, -0.0118],
        [-0.0035,  0.0047,  0.0099,  ...,  0.0006, -0.0003, -0.0056]],
       requires_grad=True)

### parameters

In [334]:
# iterate all parameters of model.
for i in model.parameters():
    print(i)

Parameter containing:
tensor([1., 2., 3.], requires_grad=True)
Parameter containing:
tensor([[-0.0164,  0.0149,  0.0121,  ..., -0.0135, -0.0038,  0.0002],
        [ 0.0115,  0.0014,  0.0051,  ..., -0.0141, -0.0063, -0.0060],
        [-0.0099,  0.0091, -0.0016,  ...,  0.0149, -0.0142, -0.0043],
        ...,
        [ 0.0119, -0.0042,  0.0209,  ...,  0.0135,  0.0135,  0.0173],
        [-0.0136,  0.0200,  0.0035,  ..., -0.0014, -0.0106, -0.0118],
        [-0.0035,  0.0047,  0.0099,  ...,  0.0006, -0.0003, -0.0056]],
       requires_grad=True)
Parameter containing:
tensor([-1.7423e-02,  1.4627e-02, -1.3636e-02, -1.8791e-02,  1.6488e-02,
        -3.2479e-02,  3.2321e-02, -1.0541e-02,  8.6383e-03, -1.0464e-02,
         3.2670e-02, -2.5496e-02,  2.9273e-02,  3.2772e-02, -2.5765e-02,
        -2.8208e-02,  1.7517e-03, -1.4240e-02, -1.8077e-02,  1.4354e-02,
        -1.2102e-02, -9.7449e-03, -1.2374e-02,  2.6612e-03, -2.9905e-02,
        -1.9698e-02, -1.6822e-02, -1.0067e-02,  7.1045e-03, -2.6527

### modules

In [336]:
# search all submdules in your model (iterate all)
for i in model.modules():
    print(i)

Net(
  (dense1): Sequential(
    (0): Linear(in_features=784, out_features=256, bias=True)
    (1): ReLU(inplace=True)
  )
  (dense2): Sequential(
    (0): Linear(in_features=256, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
)
Sequential(
  (0): Linear(in_features=784, out_features=256, bias=True)
  (1): ReLU(inplace=True)
)
Linear(in_features=784, out_features=256, bias=True)
ReLU(inplace=True)
Sequential(
  (0): Linear(in_features=256, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)
Linear(in_features=256, out_features=10, bias=True)
ReLU(inplace=True)


### require_grad

In [ ]:
# with `parameters` method, change require_grad flag all your parameters of model.

### zero_grad

In [ ]:
# with `parameters` method, change grad  all your parameters of model zero.