In [41]:
import torch
from torch import nn

### experience 01

In [11]:
# main function
class Net:
    def __init__(self):

        self.a = torch.tensor(1.0, requires_grad=True)

    def forward(self, x):
        y = self.a*(x**2)
        return y

In [12]:
# data
x1 = torch.tensor([1.0,2.0,3.0])
x2 = torch.tensor([4.0,5.0,6.0])

In [13]:
model1 = Net()
model2 = Net()

In [14]:
y1 = model1.forward(x1)
y2 = model2.forward(x2)

In [20]:
loss = (y1 + y2).sum()

In [21]:
print(model1.a.grad)
print(model2.a.grad)

None
None


In [22]:
loss.backward()

In [23]:
print(model1.a.grad)
print(model2.a.grad)

tensor(14.)
tensor(77.)


In [26]:
print(sum(x1**2))
print(sum(x2**2))

tensor(14.)
tensor(77.)


### experience 02

In [27]:
# main function
class Net:
    def __init__(self, parameter):

        self.a = parameter

    def forward(self, x):
        y = self.a*(x**2)
        return y

In [29]:
# data
x1 = torch.tensor([1.0,2.0,3.0])
x2 = torch.tensor([4.0,5.0,6.0])

In [30]:
parameter = torch.tensor(1.0, requires_grad=True)
model1 = Net(parameter)
model2 = Net(parameter)

In [31]:
y1 = model1.forward(x1)
y2 = model2.forward(x2)

In [32]:
loss = (y1 + y2).sum()

In [33]:
print(model1.a.grad)
print(model2.a.grad)

None
None


In [34]:
loss.backward()

In [35]:
print(model1.a.grad)
print(model2.a.grad)

tensor(91.)
tensor(91.)


In [36]:
print(sum(x1**2))
print(sum(x2**2))

tensor(14.)
tensor(77.)


In [37]:
print(sum(x1**2+x2**2))

tensor(91.)


### experience 03

In [39]:
# main function
class Net:
    def __init__(self):

        self.a = torch.tensor(1.0, requires_grad=True)

    def forward(self, x):
        y = self.a*(x**2)
        return y

In [40]:
# data
x1 = torch.tensor([1.0,2.0,3.0])
x2 = torch.tensor([4.0,5.0,6.0])

In [43]:
model = Net()

In [44]:
y1 = model.forward(x1)
y2 = model.forward(x2)

In [45]:
loss = (y1 + y2).sum()

In [47]:
print(model.a.grad)

None


In [48]:
loss.backward()

In [49]:
print(model.a.grad)

tensor(91.)


In [50]:
print(sum(x1**2))
print(sum(x2**2))

tensor(14.)
tensor(77.)


In [51]:
print(sum(x1**2+x2**2))

tensor(91.)


# experience 04

In [53]:
# main function
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.a = nn.parameter.Parameter (torch.tensor(1.0))

    def forward(self, x):
        y = self.a*(x**2)
        return y

In [86]:
# make parameter x1
x1 = nn.parameter.Parameter(torch.tensor([1.0,2.0,3.0]))
print(x1)

Parameter containing:
tensor([1., 2., 3.], requires_grad=True)


In [87]:
model = Net()
# make false all require_grad of model parameters
model.requires_grad_(False)

Net()

In [88]:
y1 = model.forward(x1)
print(y1)

tensor([1., 4., 9.], grad_fn=<MulBackward0>)


In [89]:
loss = y1.sum()
print(loss)

tensor(14., grad_fn=<SumBackward0>)


In [90]:
print(model.a.grad)

None


In [91]:
loss.backward()

In [92]:
print(model.a.grad)

None


In [94]:
print(x1)
print(x1.grad)

Parameter containing:
tensor([1., 2., 3.], requires_grad=True)
tensor([2., 4., 6.])


In [97]:
model._parameters

OrderedDict([('a',
              Parameter containing:
              tensor(1.))])

In [98]:
model.requires_grad_(True)

Net()

In [99]:
model._parameters

OrderedDict([('a',
              Parameter containing:
              tensor(1., requires_grad=True))])